//! Built-in weapon numbers, used only when no World at War install is
//! found: the same values the game's own weapon files hold (`weapons/sp/`),
//! as `key\\value` pairs in weapon-file units (inches, seconds). With an
//! install every weapon re-reads them from the IWD file and the map's zone.
//!
//! Generated by `research/gameplay/gen_weapon_defaults.py`; values and
//! sources are listed in `research/gameplay/WEAPONS.md`.

/// `weapons/sp/zombie_colt`
pub const ZOMBIE_COLT: &str = "\
    weaponType\\bullet\\weaponClass\\pistol\\fireType\\Single Shot\\penetrateType\\small\\boltAction\\0\\\
    damage\\20\\minDamage\\20\\maxDamageRange\\425\\minDamageRange\\1000\\meleeDamage\\150\\meleeTime\\0.5\\meleeDelay\\0.05\\\
    locNone\\1\\locHelmet\\3.5\\locHead\\3.5\\locNeck\\3.5\\locTorsoUpper\\1.25\\locTorsoLower\\1.1\\locRightArmUpper\\0.85\\locLeftArmUpper\\0.85\\locRightArmLower\\0.6\\locLeftArmLower\\0.6\\locRightHand\\0.35\\locLeftHand\\0.35\\locRightLegUpper\\0.85\\locLeftLegUpper\\0.85\\locRightLegLower\\0.6\\locLeftLegLower\\0.6\\locRightFoot\\0.35\\locLeftFoot\\0.35\\locGun\\0\\\
    fireTime\\0.075\\rechamberTime\\0.05\\clipSize\\8\\maxAmmo\\80\\startAmmo\\40\\shotCount\\1\\\
    reloadTime\\1.9\\reloadEmptyTime\\2.65\\reloadAddTime\\1.4\\reloadEmptyAddTime\\0\\reloadStartTime\\0\\reloadStartAddTime\\1.65\\reloadEndTime\\0\\segmentedReload\\0\\noPartialReload\\0\\reloadAmmoAdd\\0\\reloadStartAdd\\0\\\
    hipSpreadStandMin\\3\\hipSpreadMax\\6\\hipSpreadDuckedMin\\2.5\\hipSpreadDuckedMax\\5\\hipSpreadProneMin\\2\\hipSpreadProneMax\\4\\adsSpread\\0.2\\hipSpreadFireAdd\\1\\hipSpreadMoveAdd\\4.5\\hipSpreadTurnAdd\\0\\hipSpreadDecayRate\\4\\hipSpreadDuckedDecay\\1\\hipSpreadProneDecay\\1\\\
    adsTransInTime\\0.245\\adsTransOutTime\\0.25\\adsZoomFov\\60\\moveSpeedScale\\1\\adsMoveSpeedScale\\1.5\\sprintDurationScale\\1.2\\raiseTime\\0.4\\dropTime\\0.3\\firstRaiseTime\\0.83\\\
    hipViewKickPitchMin\\40\\hipViewKickPitchMax\\45";

/// `weapons/sp/sw_357`
pub const SW_357: &str = "\
    weaponType\\bullet\\weaponClass\\pistol\\fireType\\Single Shot\\penetrateType\\large\\boltAction\\0\\\
    damage\\1000\\minDamage\\300\\maxDamageRange\\384\\minDamageRange\\1500\\meleeDamage\\150\\meleeTime\\0.5\\meleeDelay\\0.05\\\
    locNone\\1\\locHelmet\\1.5\\locHead\\1.5\\locNeck\\1.5\\locTorsoUpper\\1.1\\locTorsoLower\\0.9\\locRightArmUpper\\0.8\\locLeftArmUpper\\0.8\\locRightArmLower\\0.8\\locLeftArmLower\\0.8\\locRightHand\\0.8\\locLeftHand\\0.8\\locRightLegUpper\\0.5\\locLeftLegUpper\\0.5\\locRightLegLower\\0.4\\locLeftLegLower\\0.4\\locRightFoot\\0.1\\locLeftFoot\\0.1\\locGun\\0\\\
    fireTime\\0.32\\rechamberTime\\0.05\\clipSize\\6\\maxAmmo\\80\\startAmmo\\80\\shotCount\\1\\\
    reloadTime\\3\\reloadEmptyTime\\3\\reloadAddTime\\3.5\\reloadEmptyAddTime\\0\\reloadStartTime\\0\\reloadStartAddTime\\3.5\\reloadEndTime\\0\\segmentedReload\\0\\noPartialReload\\0\\reloadAmmoAdd\\0\\reloadStartAdd\\0\\\
    hipSpreadStandMin\\2\\hipSpreadMax\\4\\hipSpreadDuckedMin\\1.5\\hipSpreadDuckedMax\\3\\hipSpreadProneMin\\1\\hipSpreadProneMax\\2\\adsSpread\\1.15\\hipSpreadFireAdd\\1\\hipSpreadMoveAdd\\4.5\\hipSpreadTurnAdd\\0\\hipSpreadDecayRate\\4\\hipSpreadDuckedDecay\\1\\hipSpreadProneDecay\\1\\\
    adsTransInTime\\0.245\\adsTransOutTime\\0.25\\adsZoomFov\\60\\moveSpeedScale\\0.9\\adsMoveSpeedScale\\1.2\\sprintDurationScale\\1.2\\raiseTime\\0.4\\dropTime\\0.4\\firstRaiseTime\\0.83\\\
    hipViewKickPitchMin\\100\\hipViewKickPitchMax\\100";

/// `weapons/sp/m1carbine`
pub const M1CARBINE: &str = "\
    weaponType\\bullet\\weaponClass\\rifle\\fireType\\Single Shot\\penetrateType\\medium\\boltAction\\0\\\
    damage\\68\\minDamage\\50\\maxDamageRange\\1024\\minDamageRange\\2400\\meleeDamage\\150\\meleeTime\\0.5\\meleeDelay\\0.05\\\
    locNone\\1\\locHelmet\\2.7\\locHead\\2.7\\locNeck\\2.7\\locTorsoUpper\\1.25\\locTorsoLower\\1.25\\locRightArmUpper\\0.8\\locLeftArmUpper\\0.8\\locRightArmLower\\0.7\\locLeftArmLower\\0.7\\locRightHand\\0.6\\locLeftHand\\0.6\\locRightLegUpper\\0.8\\locLeftLegUpper\\0.8\\locRightLegLower\\0.7\\locLeftLegLower\\0.7\\locRightFoot\\0.6\\locLeftFoot\\0.6\\locGun\\0\\\
    fireTime\\0.135\\rechamberTime\\0.1\\clipSize\\15\\maxAmmo\\120\\startAmmo\\120\\shotCount\\1\\\
    reloadTime\\2.9\\reloadEmptyTime\\3.7\\reloadAddTime\\2.2\\reloadEmptyAddTime\\0\\reloadStartTime\\0\\reloadStartAddTime\\2.3\\reloadEndTime\\0\\segmentedReload\\0\\noPartialReload\\0\\reloadAmmoAdd\\0\\reloadStartAdd\\0\\\
    hipSpreadStandMin\\1\\hipSpreadMax\\5\\hipSpreadDuckedMin\\0.75\\hipSpreadDuckedMax\\4\\hipSpreadProneMin\\0.5\\hipSpreadProneMax\\3\\adsSpread\\0\\hipSpreadFireAdd\\0.6\\hipSpreadMoveAdd\\5\\hipSpreadTurnAdd\\0\\hipSpreadDecayRate\\4\\hipSpreadDuckedDecay\\1.05\\hipSpreadProneDecay\\1.1\\\
    adsTransInTime\\0.3\\adsTransOutTime\\0.4\\adsZoomFov\\45\\moveSpeedScale\\0.9\\adsMoveSpeedScale\\0.9\\sprintDurationScale\\0.9\\raiseTime\\0.5\\dropTime\\0.4\\firstRaiseTime\\1.4\\\
    hipViewKickPitchMin\\15\\hipViewKickPitchMax\\50";

/// `weapons/sp/m1garand`
pub const M1GARAND: &str = "\
    weaponType\\bullet\\weaponClass\\rifle\\fireType\\Single Shot\\penetrateType\\medium\\boltAction\\0\\\
    damage\\68\\minDamage\\50\\maxDamageRange\\1024\\minDamageRange\\2400\\meleeDamage\\150\\meleeTime\\0.5\\meleeDelay\\0.05\\\
    locNone\\1\\locHelmet\\2.7\\locHead\\2.7\\locNeck\\2.7\\locTorsoUpper\\1.25\\locTorsoLower\\1.25\\locRightArmUpper\\0.8\\locLeftArmUpper\\0.8\\locRightArmLower\\0.7\\locLeftArmLower\\0.7\\locRightHand\\0.6\\locLeftHand\\0.6\\locRightLegUpper\\0.8\\locLeftLegUpper\\0.8\\locRightLegLower\\0.7\\locLeftLegLower\\0.7\\locRightFoot\\0.6\\locLeftFoot\\0.6\\locGun\\0\\\
    fireTime\\0.135\\rechamberTime\\0\\clipSize\\8\\maxAmmo\\128\\startAmmo\\96\\shotCount\\1\\\
    reloadTime\\3.4\\reloadEmptyTime\\1.6\\reloadAddTime\\2.5\\reloadEmptyAddTime\\0\\reloadStartTime\\0\\reloadStartAddTime\\0\\reloadEndTime\\0\\segmentedReload\\0\\noPartialReload\\0\\reloadAmmoAdd\\0\\reloadStartAdd\\0\\\
    hipSpreadStandMin\\1\\hipSpreadMax\\5\\hipSpreadDuckedMin\\0.75\\hipSpreadDuckedMax\\4\\hipSpreadProneMin\\0.5\\hipSpreadProneMax\\3\\adsSpread\\0.2\\hipSpreadFireAdd\\0.6\\hipSpreadMoveAdd\\5\\hipSpreadTurnAdd\\0\\hipSpreadDecayRate\\4\\hipSpreadDuckedDecay\\1.05\\hipSpreadProneDecay\\1.1\\\
    adsTransInTime\\0.25\\adsTransOutTime\\0.25\\adsZoomFov\\40\\moveSpeedScale\\0.9\\adsMoveSpeedScale\\0.9\\sprintDurationScale\\0.9\\raiseTime\\0.8\\dropTime\\0.25\\firstRaiseTime\\1\\\
    hipViewKickPitchMin\\15\\hipViewKickPitchMax\\50";

/// `weapons/sp/m1garand_gl`
pub const M1GARAND_GL: &str = "\
    weaponType\\bullet\\weaponClass\\rifle\\fireType\\Single Shot\\penetrateType\\medium\\boltAction\\0\\\
    damage\\68\\minDamage\\50\\maxDamageRange\\1024\\minDamageRange\\2400\\meleeDamage\\150\\meleeTime\\0.5\\meleeDelay\\0.05\\\
    locNone\\1\\locHelmet\\2.7\\locHead\\2.7\\locNeck\\2.7\\locTorsoUpper\\1.25\\locTorsoLower\\1.25\\locRightArmUpper\\0.8\\locLeftArmUpper\\0.8\\locRightArmLower\\0.7\\locLeftArmLower\\0.7\\locRightHand\\0.6\\locLeftHand\\0.6\\locRightLegUpper\\0.8\\locLeftLegUpper\\0.8\\locRightLegLower\\0.7\\locLeftLegLower\\0.7\\locRightFoot\\0.6\\locLeftFoot\\0.6\\locGun\\0\\\
    fireTime\\0.135\\rechamberTime\\0\\clipSize\\8\\maxAmmo\\128\\startAmmo\\96\\shotCount\\1\\\
    reloadTime\\3.4\\reloadEmptyTime\\1.6\\reloadAddTime\\2.5\\reloadEmptyAddTime\\0\\reloadStartTime\\0\\reloadStartAddTime\\0\\reloadEndTime\\0\\segmentedReload\\0\\noPartialReload\\0\\reloadAmmoAdd\\0\\reloadStartAdd\\0\\\
    hipSpreadStandMin\\1\\hipSpreadMax\\5\\hipSpreadDuckedMin\\0.75\\hipSpreadDuckedMax\\4\\hipSpreadProneMin\\0.5\\hipSpreadProneMax\\3\\adsSpread\\0.2\\hipSpreadFireAdd\\0.6\\hipSpreadMoveAdd\\5\\hipSpreadTurnAdd\\0\\hipSpreadDecayRate\\4\\hipSpreadDuckedDecay\\1.05\\hipSpreadProneDecay\\1.1\\\
    adsTransInTime\\0.25\\adsTransOutTime\\0.25\\adsZoomFov\\40\\moveSpeedScale\\0.9\\adsMoveSpeedScale\\0.9\\sprintDurationScale\\0.9\\raiseTime\\0.8\\dropTime\\0.25\\firstRaiseTime\\1\\\
    hipViewKickPitchMin\\15\\hipViewKickPitchMax\\50";

/// `weapons/sp/gewehr43`
pub const GEWEHR43: &str = "\
    weaponType\\bullet\\weaponClass\\rifle\\fireType\\Single Shot\\penetrateType\\medium\\boltAction\\0\\\
    damage\\90\\minDamage\\50\\maxDamageRange\\1024\\minDamageRange\\2400\\meleeDamage\\150\\meleeTime\\0.5\\meleeDelay\\0.05\\\
    locNone\\1\\locHelmet\\2.7\\locHead\\2.7\\locNeck\\2.7\\locTorsoUpper\\1.25\\locTorsoLower\\1.25\\locRightArmUpper\\0.8\\locLeftArmUpper\\0.8\\locRightArmLower\\0.7\\locLeftArmLower\\0.7\\locRightHand\\0.6\\locLeftHand\\0.6\\locRightLegUpper\\0.8\\locLeftLegUpper\\0.8\\locRightLegLower\\0.7\\locLeftLegLower\\0.7\\locRightFoot\\0.6\\locLeftFoot\\0.6\\locGun\\0\\\
    fireTime\\0.125\\rechamberTime\\0.1\\clipSize\\10\\maxAmmo\\120\\startAmmo\\96\\shotCount\\1\\\
    reloadTime\\3\\reloadEmptyTime\\4\\reloadAddTime\\2.05\\reloadEmptyAddTime\\0\\reloadStartTime\\0\\reloadStartAddTime\\2.35\\reloadEndTime\\0\\segmentedReload\\0\\noPartialReload\\0\\reloadAmmoAdd\\0\\reloadStartAdd\\0\\\
    hipSpreadStandMin\\1\\hipSpreadMax\\5\\hipSpreadDuckedMin\\0.75\\hipSpreadDuckedMax\\4\\hipSpreadProneMin\\0.5\\hipSpreadProneMax\\3\\adsSpread\\0\\hipSpreadFireAdd\\0.6\\hipSpreadMoveAdd\\5\\hipSpreadTurnAdd\\0\\hipSpreadDecayRate\\4\\hipSpreadDuckedDecay\\1.05\\hipSpreadProneDecay\\1.1\\\
    adsTransInTime\\0.3\\adsTransOutTime\\0.4\\adsZoomFov\\40\\moveSpeedScale\\0.9\\adsMoveSpeedScale\\0.9\\sprintDurationScale\\0.9\\raiseTime\\0.6\\dropTime\\0.5\\firstRaiseTime\\1\\\
    hipViewKickPitchMin\\15\\hipViewKickPitchMax\\50";

/// `weapons/sp/kar98k`
pub const KAR98K: &str = "\
    weaponType\\bullet\\weaponClass\\rifle\\fireType\\Single Shot\\penetrateType\\medium\\boltAction\\1\\\
    damage\\100\\minDamage\\80\\maxDamageRange\\1200\\minDamageRange\\2200\\meleeDamage\\150\\meleeTime\\0.5\\meleeDelay\\0.05\\\
    locNone\\1\\locHelmet\\1\\locHead\\3.5\\locNeck\\3.5\\locTorsoUpper\\1.8\\locTorsoLower\\1.7\\locRightArmUpper\\1\\locLeftArmUpper\\1\\locRightArmLower\\1\\locLeftArmLower\\1\\locRightHand\\0.7\\locLeftHand\\0.7\\locRightLegUpper\\1\\locLeftLegUpper\\1\\locRightLegLower\\1\\locLeftLegLower\\1\\locRightFoot\\0.7\\locLeftFoot\\0.7\\locGun\\0\\\
    fireTime\\0.33\\rechamberTime\\1\\clipSize\\5\\maxAmmo\\50\\startAmmo\\50\\shotCount\\1\\\
    reloadTime\\2.5\\reloadEmptyTime\\2.5\\reloadAddTime\\1.65\\reloadEmptyAddTime\\0\\reloadStartTime\\0\\reloadStartAddTime\\1.65\\reloadEndTime\\0\\segmentedReload\\0\\noPartialReload\\0\\reloadAmmoAdd\\0\\reloadStartAdd\\0\\\
    hipSpreadStandMin\\8\\hipSpreadMax\\10\\hipSpreadDuckedMin\\7.5\\hipSpreadDuckedMax\\9.5\\hipSpreadProneMin\\7\\hipSpreadProneMax\\9\\adsSpread\\0.05\\hipSpreadFireAdd\\1\\hipSpreadMoveAdd\\5\\hipSpreadTurnAdd\\0\\hipSpreadDecayRate\\5\\hipSpreadDuckedDecay\\1\\hipSpreadProneDecay\\1\\\
    adsTransInTime\\0.2\\adsTransOutTime\\0.4\\adsZoomFov\\40\\moveSpeedScale\\0.9\\adsMoveSpeedScale\\0.9\\sprintDurationScale\\0.9\\raiseTime\\0.5\\dropTime\\0.4\\firstRaiseTime\\0.9\\\
    hipViewKickPitchMin\\40\\hipViewKickPitchMax\\80";

/// `weapons/sp/springfield`
pub const SPRINGFIELD: &str = "\
    weaponType\\bullet\\weaponClass\\rifle\\fireType\\Single Shot\\penetrateType\\medium\\boltAction\\1\\\
    damage\\100\\minDamage\\80\\maxDamageRange\\1200\\minDamageRange\\2200\\meleeDamage\\150\\meleeTime\\0.5\\meleeDelay\\0.05\\\
    locNone\\1\\locHelmet\\0.5\\locHead\\2\\locNeck\\2\\locTorsoUpper\\1.2\\locTorsoLower\\0.9\\locRightArmUpper\\0.8\\locLeftArmUpper\\0.8\\locRightArmLower\\0.6\\locLeftArmLower\\0.6\\locRightHand\\0.1\\locLeftHand\\0.1\\locRightLegUpper\\0.5\\locLeftLegUpper\\0.5\\locRightLegLower\\0.4\\locLeftLegLower\\0.4\\locRightFoot\\0.1\\locLeftFoot\\0.1\\locGun\\0\\\
    fireTime\\0.33\\rechamberTime\\1\\clipSize\\5\\maxAmmo\\50\\startAmmo\\50\\shotCount\\1\\\
    reloadTime\\3.2\\reloadEmptyTime\\3.2\\reloadAddTime\\2\\reloadEmptyAddTime\\0\\reloadStartTime\\0\\reloadStartAddTime\\0\\reloadEndTime\\0\\segmentedReload\\0\\noPartialReload\\0\\reloadAmmoAdd\\0\\reloadStartAdd\\0\\\
    hipSpreadStandMin\\8\\hipSpreadMax\\10\\hipSpreadDuckedMin\\7.5\\hipSpreadDuckedMax\\9.5\\hipSpreadProneMin\\7\\hipSpreadProneMax\\9\\adsSpread\\0.05\\hipSpreadFireAdd\\1\\hipSpreadMoveAdd\\5\\hipSpreadTurnAdd\\0\\hipSpreadDecayRate\\5\\hipSpreadDuckedDecay\\1\\hipSpreadProneDecay\\1\\\
    adsTransInTime\\0.2\\adsTransOutTime\\0.4\\adsZoomFov\\40\\moveSpeedScale\\0.9\\adsMoveSpeedScale\\0.9\\sprintDurationScale\\0.9\\raiseTime\\0.5\\dropTime\\0.4\\firstRaiseTime\\0.75\\\
    hipViewKickPitchMin\\40\\hipViewKickPitchMax\\80";

/// `weapons/sp/kar98k_scoped_zombie`
pub const KAR98K_SCOPED_ZOMBIE: &str = "\
    weaponType\\bullet\\weaponClass\\rifle\\fireType\\Single Shot\\penetrateType\\medium\\boltAction\\1\\\
    damage\\300\\minDamage\\300\\maxDamageRange\\4000\\minDamageRange\\5000\\meleeDamage\\150\\meleeTime\\0.5\\meleeDelay\\0.05\\\
    locNone\\1\\locHelmet\\3\\locHead\\10\\locNeck\\5\\locTorsoUpper\\2.25\\locTorsoLower\\2.25\\locRightArmUpper\\0.8\\locLeftArmUpper\\0.8\\locRightArmLower\\0.8\\locLeftArmLower\\0.8\\locRightHand\\0.8\\locLeftHand\\0.8\\locRightLegUpper\\0.8\\locLeftLegUpper\\0.8\\locRightLegLower\\0.8\\locLeftLegLower\\0.8\\locRightFoot\\0.8\\locLeftFoot\\0.8\\locGun\\0\\\
    fireTime\\0.33\\rechamberTime\\1.2\\clipSize\\5\\maxAmmo\\50\\startAmmo\\50\\shotCount\\1\\\
    reloadTime\\0.6\\reloadEmptyTime\\0.6\\reloadAddTime\\0.2\\reloadEmptyAddTime\\0\\reloadStartTime\\1.8\\reloadStartAddTime\\1.4\\reloadEndTime\\0.77\\segmentedReload\\1\\noPartialReload\\1\\reloadAmmoAdd\\1\\reloadStartAdd\\1\\\
    hipSpreadStandMin\\8\\hipSpreadMax\\10\\hipSpreadDuckedMin\\7.5\\hipSpreadDuckedMax\\9.5\\hipSpreadProneMin\\7\\hipSpreadProneMax\\9\\adsSpread\\0\\hipSpreadFireAdd\\1\\hipSpreadMoveAdd\\5\\hipSpreadTurnAdd\\0\\hipSpreadDecayRate\\5\\hipSpreadDuckedDecay\\1\\hipSpreadProneDecay\\1\\\
    adsTransInTime\\0.3\\adsTransOutTime\\0.4\\adsZoomFov\\10\\moveSpeedScale\\0.9\\adsMoveSpeedScale\\0.75\\sprintDurationScale\\0.9\\raiseTime\\0.7\\dropTime\\0.5\\firstRaiseTime\\0.85\\\
    hipViewKickPitchMin\\95\\hipViewKickPitchMax\\100";

/// `weapons/sp/ptrs41_zombie`
pub const PTRS41_ZOMBIE: &str = "\
    weaponType\\bullet\\weaponClass\\rifle\\fireType\\Single Shot\\penetrateType\\large\\boltAction\\0\\\
    damage\\1000\\minDamage\\1000\\maxDamageRange\\4000\\minDamageRange\\5000\\meleeDamage\\150\\meleeTime\\0.5\\meleeDelay\\0.05\\\
    locNone\\1\\locHelmet\\3\\locHead\\10\\locNeck\\5\\locTorsoUpper\\2.25\\locTorsoLower\\2.25\\locRightArmUpper\\2\\locLeftArmUpper\\2\\locRightArmLower\\1\\locLeftArmLower\\1\\locRightHand\\1\\locLeftHand\\1\\locRightLegUpper\\1\\locLeftLegUpper\\1\\locRightLegLower\\1\\locLeftLegLower\\1\\locRightFoot\\1\\locLeftFoot\\1\\locGun\\0\\\
    fireTime\\0.8\\rechamberTime\\0\\clipSize\\5\\maxAmmo\\60\\startAmmo\\30\\shotCount\\1\\\
    reloadTime\\4\\reloadEmptyTime\\5.3\\reloadAddTime\\2.5\\reloadEmptyAddTime\\0\\reloadStartTime\\0\\reloadStartAddTime\\0\\reloadEndTime\\0\\segmentedReload\\0\\noPartialReload\\0\\reloadAmmoAdd\\0\\reloadStartAdd\\0\\\
    hipSpreadStandMin\\8\\hipSpreadMax\\10\\hipSpreadDuckedMin\\7.5\\hipSpreadDuckedMax\\9.5\\hipSpreadProneMin\\7\\hipSpreadProneMax\\9\\adsSpread\\0\\hipSpreadFireAdd\\1\\hipSpreadMoveAdd\\5\\hipSpreadTurnAdd\\0\\hipSpreadDecayRate\\5\\hipSpreadDuckedDecay\\1\\hipSpreadProneDecay\\1\\\
    adsTransInTime\\0.4\\adsTransOutTime\\0.6\\adsZoomFov\\10\\moveSpeedScale\\0.75\\adsMoveSpeedScale\\0.75\\sprintDurationScale\\0.75\\raiseTime\\1.1\\dropTime\\0.85\\firstRaiseTime\\1.1\\\
    hipViewKickPitchMin\\95\\hipViewKickPitchMax\\100";

/// `weapons/sp/thompson`
pub const THOMPSON: &str = "\
    weaponType\\bullet\\weaponClass\\smg\\fireType\\Full Auto\\penetrateType\\medium\\boltAction\\0\\\
    damage\\120\\minDamage\\80\\maxDamageRange\\800\\minDamageRange\\1800\\meleeDamage\\150\\meleeTime\\0.5\\meleeDelay\\0.05\\\
    locNone\\1\\locHelmet\\4\\locHead\\4\\locNeck\\1\\locTorsoUpper\\1\\locTorsoLower\\1\\locRightArmUpper\\1\\locLeftArmUpper\\1\\locRightArmLower\\1\\locLeftArmLower\\1\\locRightHand\\1\\locLeftHand\\1\\locRightLegUpper\\1\\locLeftLegUpper\\1\\locRightLegLower\\1\\locLeftLegLower\\1\\locRightFoot\\1\\locLeftFoot\\1\\locGun\\0\\\
    fireTime\\0.08\\rechamberTime\\0\\clipSize\\20\\maxAmmo\\200\\startAmmo\\200\\shotCount\\1\\\
    reloadTime\\2.1\\reloadEmptyTime\\2.45\\reloadAddTime\\1.6\\reloadEmptyAddTime\\0\\reloadStartTime\\0\\reloadStartAddTime\\1.2\\reloadEndTime\\0\\segmentedReload\\0\\noPartialReload\\0\\reloadAmmoAdd\\0\\reloadStartAdd\\0\\\
    hipSpreadStandMin\\1.5\\hipSpreadMax\\6\\hipSpreadDuckedMin\\1.25\\hipSpreadDuckedMax\\5\\hipSpreadProneMin\\1\\hipSpreadProneMax\\4\\adsSpread\\0\\hipSpreadFireAdd\\0.52\\hipSpreadMoveAdd\\4\\hipSpreadTurnAdd\\0\\hipSpreadDecayRate\\4\\hipSpreadDuckedDecay\\1\\hipSpreadProneDecay\\1\\\
    adsTransInTime\\0.22\\adsTransOutTime\\0.3\\adsZoomFov\\55\\moveSpeedScale\\1\\adsMoveSpeedScale\\1.3\\sprintDurationScale\\1\\raiseTime\\0.44\\dropTime\\0.38\\firstRaiseTime\\0.6\\\
    hipViewKickPitchMin\\35\\hipViewKickPitchMax\\50";

/// `weapons/sp/mp40`
pub const MP40: &str = "\
    weaponType\\bullet\\weaponClass\\smg\\fireType\\Full Auto\\penetrateType\\small\\boltAction\\0\\\
    damage\\100\\minDamage\\60\\maxDamageRange\\800\\minDamageRange\\1800\\meleeDamage\\150\\meleeTime\\0.5\\meleeDelay\\0.05\\\
    locNone\\1\\locHelmet\\4\\locHead\\4\\locNeck\\1\\locTorsoUpper\\1\\locTorsoLower\\1\\locRightArmUpper\\1\\locLeftArmUpper\\1\\locRightArmLower\\1\\locLeftArmLower\\1\\locRightHand\\1\\locLeftHand\\1\\locRightLegUpper\\1\\locLeftLegUpper\\1\\locRightLegLower\\1\\locLeftLegLower\\1\\locRightFoot\\1\\locLeftFoot\\1\\locGun\\0\\\
    fireTime\\0.112\\rechamberTime\\0.1\\clipSize\\32\\maxAmmo\\192\\startAmmo\\192\\shotCount\\1\\\
    reloadTime\\2.3\\reloadEmptyTime\\2.9\\reloadAddTime\\1.85\\reloadEmptyAddTime\\0\\reloadStartTime\\0\\reloadStartAddTime\\1.85\\reloadEndTime\\0\\segmentedReload\\0\\noPartialReload\\0\\reloadAmmoAdd\\0\\reloadStartAdd\\0\\\
    hipSpreadStandMin\\1.5\\hipSpreadMax\\6\\hipSpreadDuckedMin\\1.25\\hipSpreadDuckedMax\\5\\hipSpreadProneMin\\1\\hipSpreadProneMax\\4\\adsSpread\\0\\hipSpreadFireAdd\\0.52\\hipSpreadMoveAdd\\4\\hipSpreadTurnAdd\\0\\hipSpreadDecayRate\\4\\hipSpreadDuckedDecay\\1\\hipSpreadProneDecay\\1\\\
    adsTransInTime\\0.25\\adsTransOutTime\\0.3\\adsZoomFov\\55\\moveSpeedScale\\1\\adsMoveSpeedScale\\1.3\\sprintDurationScale\\1\\raiseTime\\0.35\\dropTime\\0.3\\firstRaiseTime\\1.33\\\
    hipViewKickPitchMin\\35\\hipViewKickPitchMax\\50";

/// `weapons/sp/stg44`
pub const STG44: &str = "\
    weaponType\\bullet\\weaponClass\\smg\\fireType\\Full Auto\\penetrateType\\medium\\boltAction\\0\\\
    damage\\100\\minDamage\\70\\maxDamageRange\\1024\\minDamageRange\\2400\\meleeDamage\\150\\meleeTime\\0.5\\meleeDelay\\0.05\\\
    locNone\\1\\locHelmet\\2.7\\locHead\\2.7\\locNeck\\2.7\\locTorsoUpper\\1\\locTorsoLower\\0.9\\locRightArmUpper\\0.6\\locLeftArmUpper\\0.6\\locRightArmLower\\0.5\\locLeftArmLower\\0.5\\locRightHand\\0.3\\locLeftHand\\0.3\\locRightLegUpper\\0.6\\locLeftLegUpper\\0.6\\locRightLegLower\\0.5\\locLeftLegLower\\0.5\\locRightFoot\\0.3\\locLeftFoot\\0.3\\locGun\\0\\\
    fireTime\\0.112\\rechamberTime\\0.1\\clipSize\\30\\maxAmmo\\180\\startAmmo\\180\\shotCount\\1\\\
    reloadTime\\2.15\\reloadEmptyTime\\2.8\\reloadAddTime\\1.4\\reloadEmptyAddTime\\0\\reloadStartTime\\0\\reloadStartAddTime\\1.4\\reloadEndTime\\0\\segmentedReload\\0\\noPartialReload\\0\\reloadAmmoAdd\\0\\reloadStartAdd\\0\\\
    hipSpreadStandMin\\2\\hipSpreadMax\\8\\hipSpreadDuckedMin\\1.8\\hipSpreadDuckedMax\\6.5\\hipSpreadProneMin\\1.5\\hipSpreadProneMax\\5\\adsSpread\\0\\hipSpreadFireAdd\\0.56\\hipSpreadMoveAdd\\5\\hipSpreadTurnAdd\\0\\hipSpreadDecayRate\\4\\hipSpreadDuckedDecay\\1.05\\hipSpreadProneDecay\\1.1\\\
    adsTransInTime\\0.35\\adsTransOutTime\\0.4\\adsZoomFov\\45\\moveSpeedScale\\1\\adsMoveSpeedScale\\1.3\\sprintDurationScale\\1\\raiseTime\\0.6\\dropTime\\0.4\\firstRaiseTime\\1\\\
    hipViewKickPitchMin\\45\\hipViewKickPitchMax\\55";

/// `weapons/sp/ppsh`
pub const PPSH: &str = "\
    weaponType\\bullet\\weaponClass\\smg\\fireType\\Full Auto\\penetrateType\\small\\boltAction\\0\\\
    damage\\100\\minDamage\\60\\maxDamageRange\\800\\minDamageRange\\1500\\meleeDamage\\150\\meleeTime\\0.5\\meleeDelay\\0.05\\\
    locNone\\1\\locHelmet\\4\\locHead\\4\\locNeck\\1\\locTorsoUpper\\1\\locTorsoLower\\1\\locRightArmUpper\\1\\locLeftArmUpper\\1\\locRightArmLower\\1\\locLeftArmLower\\1\\locRightHand\\1\\locLeftHand\\1\\locRightLegUpper\\1\\locLeftLegUpper\\1\\locRightLegLower\\1\\locLeftLegLower\\1\\locRightFoot\\1\\locLeftFoot\\1\\locGun\\0\\\
    fireTime\\0.048\\rechamberTime\\0.1\\clipSize\\71\\maxAmmo\\355\\startAmmo\\355\\shotCount\\1\\\
    reloadTime\\2.1\\reloadEmptyTime\\2.8\\reloadAddTime\\1.9\\reloadEmptyAddTime\\0\\reloadStartTime\\0\\reloadStartAddTime\\1.7\\reloadEndTime\\0\\segmentedReload\\0\\noPartialReload\\0\\reloadAmmoAdd\\0\\reloadStartAdd\\0\\\
    hipSpreadStandMin\\2\\hipSpreadMax\\5\\hipSpreadDuckedMin\\1.75\\hipSpreadDuckedMax\\4.5\\hipSpreadProneMin\\1.5\\hipSpreadProneMax\\4\\adsSpread\\0\\hipSpreadFireAdd\\0.52\\hipSpreadMoveAdd\\4\\hipSpreadTurnAdd\\0\\hipSpreadDecayRate\\4\\hipSpreadDuckedDecay\\1\\hipSpreadProneDecay\\1\\\
    adsTransInTime\\0.2\\adsTransOutTime\\0.28\\adsZoomFov\\55\\moveSpeedScale\\1\\adsMoveSpeedScale\\1.3\\sprintDurationScale\\1\\raiseTime\\0.44\\dropTime\\0.38\\firstRaiseTime\\0.65\\\
    hipViewKickPitchMin\\20\\hipViewKickPitchMax\\35";

/// `weapons/sp/bar`
pub const BAR: &str = "\
    weaponType\\bullet\\weaponClass\\mg\\fireType\\Full Auto\\penetrateType\\medium\\boltAction\\0\\\
    damage\\100\\minDamage\\85\\maxDamageRange\\1024\\minDamageRange\\2400\\meleeDamage\\150\\meleeTime\\0.5\\meleeDelay\\0.05\\\
    locNone\\1\\locHelmet\\2.7\\locHead\\2.7\\locNeck\\2.7\\locTorsoUpper\\2\\locTorsoLower\\2\\locRightArmUpper\\1.7\\locLeftArmUpper\\1.7\\locRightArmLower\\1.5\\locLeftArmLower\\1.5\\locRightHand\\1.4\\locLeftHand\\1.4\\locRightLegUpper\\1.7\\locLeftLegUpper\\1.7\\locRightLegLower\\1.5\\locLeftLegLower\\1.5\\locRightFoot\\1.4\\locLeftFoot\\1.4\\locGun\\0\\\
    fireTime\\0.16\\rechamberTime\\0.1\\clipSize\\20\\maxAmmo\\140\\startAmmo\\140\\shotCount\\1\\\
    reloadTime\\2.75\\reloadEmptyTime\\3.25\\reloadAddTime\\1.95\\reloadEmptyAddTime\\0\\reloadStartTime\\0\\reloadStartAddTime\\1.75\\reloadEndTime\\0\\segmentedReload\\0\\noPartialReload\\0\\reloadAmmoAdd\\0\\reloadStartAdd\\0\\\
    hipSpreadStandMin\\2\\hipSpreadMax\\8\\hipSpreadDuckedMin\\1.8\\hipSpreadDuckedMax\\6.5\\hipSpreadProneMin\\1.5\\hipSpreadProneMax\\5\\adsSpread\\0.4\\hipSpreadFireAdd\\0.56\\hipSpreadMoveAdd\\5\\hipSpreadTurnAdd\\0\\hipSpreadDecayRate\\4\\hipSpreadDuckedDecay\\1.05\\hipSpreadProneDecay\\1.1\\\
    adsTransInTime\\0.32\\adsTransOutTime\\0.37\\adsZoomFov\\35\\moveSpeedScale\\1\\adsMoveSpeedScale\\0.85\\sprintDurationScale\\0.9\\raiseTime\\0.6\\dropTime\\0.4\\firstRaiseTime\\0.65\\\
    hipViewKickPitchMin\\45\\hipViewKickPitchMax\\55";

/// `weapons/sp/fg42_bipod`
pub const FG42_BIPOD: &str = "\
    weaponType\\bullet\\weaponClass\\mg\\fireType\\Full Auto\\penetrateType\\small\\boltAction\\0\\\
    damage\\100\\minDamage\\85\\maxDamageRange\\1024\\minDamageRange\\2400\\meleeDamage\\150\\meleeTime\\0.5\\meleeDelay\\0.05\\\
    locNone\\1\\locHelmet\\2.7\\locHead\\2.7\\locNeck\\2.7\\locTorsoUpper\\2\\locTorsoLower\\2\\locRightArmUpper\\1.7\\locLeftArmUpper\\1.7\\locRightArmLower\\1.5\\locLeftArmLower\\1.5\\locRightHand\\1.4\\locLeftHand\\1.4\\locRightLegUpper\\1.7\\locLeftLegUpper\\1.7\\locRightLegLower\\1.5\\locLeftLegLower\\1.5\\locRightFoot\\1.4\\locLeftFoot\\1.4\\locGun\\0\\\
    fireTime\\0.064\\rechamberTime\\0.1\\clipSize\\32\\maxAmmo\\192\\startAmmo\\192\\shotCount\\1\\\
    reloadTime\\2.4\\reloadEmptyTime\\3.5\\reloadAddTime\\1.85\\reloadEmptyAddTime\\0\\reloadStartTime\\0\\reloadStartAddTime\\1.75\\reloadEndTime\\0\\segmentedReload\\0\\noPartialReload\\0\\reloadAmmoAdd\\0\\reloadStartAdd\\0\\\
    hipSpreadStandMin\\2\\hipSpreadMax\\8\\hipSpreadDuckedMin\\1.8\\hipSpreadDuckedMax\\6.5\\hipSpreadProneMin\\1.5\\hipSpreadProneMax\\5\\adsSpread\\0.4\\hipSpreadFireAdd\\0.56\\hipSpreadMoveAdd\\5\\hipSpreadTurnAdd\\0\\hipSpreadDecayRate\\4\\hipSpreadDuckedDecay\\1.05\\hipSpreadProneDecay\\1.1\\\
    adsTransInTime\\0.22\\adsTransOutTime\\0.4\\adsZoomFov\\35\\moveSpeedScale\\0.8\\adsMoveSpeedScale\\0.8\\sprintDurationScale\\0.8\\raiseTime\\0.7\\dropTime\\0.5\\firstRaiseTime\\0.7\\\
    hipViewKickPitchMin\\45\\hipViewKickPitchMax\\55";

/// `weapons/sp/mg42_bipod`
pub const MG42_BIPOD: &str = "\
    weaponType\\bullet\\weaponClass\\mg\\fireType\\Full Auto\\penetrateType\\large\\boltAction\\0\\\
    damage\\130\\minDamage\\90\\maxDamageRange\\1024\\minDamageRange\\2400\\meleeDamage\\150\\meleeTime\\0.5\\meleeDelay\\0.05\\\
    locNone\\1\\locHelmet\\3\\locHead\\3\\locNeck\\1\\locTorsoUpper\\1\\locTorsoLower\\1\\locRightArmUpper\\1\\locLeftArmUpper\\1\\locRightArmLower\\1\\locLeftArmLower\\1\\locRightHand\\1\\locLeftHand\\1\\locRightLegUpper\\1\\locLeftLegUpper\\1\\locRightLegLower\\1\\locLeftLegLower\\1\\locRightFoot\\1\\locLeftFoot\\1\\locGun\\0\\\
    fireTime\\0.064\\rechamberTime\\0.1\\clipSize\\125\\maxAmmo\\500\\startAmmo\\500\\shotCount\\1\\\
    reloadTime\\4.5\\reloadEmptyTime\\4.5\\reloadAddTime\\2\\reloadEmptyAddTime\\0\\reloadStartTime\\0\\reloadStartAddTime\\2\\reloadEndTime\\0\\segmentedReload\\0\\noPartialReload\\0\\reloadAmmoAdd\\0\\reloadStartAdd\\0\\\
    hipSpreadStandMin\\3.7\\hipSpreadMax\\6\\hipSpreadDuckedMin\\2.5\\hipSpreadDuckedMax\\5\\hipSpreadProneMin\\1\\hipSpreadProneMax\\4\\adsSpread\\0\\hipSpreadFireAdd\\0.6\\hipSpreadMoveAdd\\5\\hipSpreadTurnAdd\\0\\hipSpreadDecayRate\\4\\hipSpreadDuckedDecay\\1.05\\hipSpreadProneDecay\\1.1\\\
    adsTransInTime\\0.7\\adsTransOutTime\\0.9\\adsZoomFov\\50\\moveSpeedScale\\0.75\\adsMoveSpeedScale\\0.75\\sprintDurationScale\\0.75\\raiseTime\\0.8\\dropTime\\0.8\\firstRaiseTime\\0.8\\\
    hipViewKickPitchMin\\60\\hipViewKickPitchMax\\70";

/// `weapons/sp/30cal_bipod`
pub const CAL30_BIPOD: &str = "\
    weaponType\\bullet\\weaponClass\\mg\\fireType\\Full Auto\\penetrateType\\large\\boltAction\\0\\\
    damage\\130\\minDamage\\90\\maxDamageRange\\1024\\minDamageRange\\2400\\meleeDamage\\150\\meleeTime\\0.5\\meleeDelay\\0.05\\\
    locNone\\1\\locHelmet\\3\\locHead\\3\\locNeck\\1\\locTorsoUpper\\1\\locTorsoLower\\1\\locRightArmUpper\\1\\locLeftArmUpper\\1\\locRightArmLower\\1\\locLeftArmLower\\1\\locRightHand\\1\\locLeftHand\\1\\locRightLegUpper\\1\\locLeftLegUpper\\1\\locRightLegLower\\1\\locLeftLegLower\\1\\locRightFoot\\1\\locLeftFoot\\1\\locGun\\0\\\
    fireTime\\0.096\\rechamberTime\\0.1\\clipSize\\125\\maxAmmo\\500\\startAmmo\\500\\shotCount\\1\\\
    reloadTime\\7\\reloadEmptyTime\\6\\reloadAddTime\\4.75\\reloadEmptyAddTime\\0\\reloadStartTime\\0\\reloadStartAddTime\\0\\reloadEndTime\\0\\segmentedReload\\0\\noPartialReload\\0\\reloadAmmoAdd\\0\\reloadStartAdd\\0\\\
    hipSpreadStandMin\\4\\hipSpreadMax\\10\\hipSpreadDuckedMin\\3.5\\hipSpreadDuckedMax\\8\\hipSpreadProneMin\\3\\hipSpreadProneMax\\6\\adsSpread\\0\\hipSpreadFireAdd\\0.6\\hipSpreadMoveAdd\\5\\hipSpreadTurnAdd\\0\\hipSpreadDecayRate\\4\\hipSpreadDuckedDecay\\1.05\\hipSpreadProneDecay\\1.1\\\
    adsTransInTime\\0.22\\adsTransOutTime\\0.4\\adsZoomFov\\50\\moveSpeedScale\\0.75\\adsMoveSpeedScale\\0.75\\sprintDurationScale\\0.75\\raiseTime\\0.9\\dropTime\\0.83\\firstRaiseTime\\1.5\\\
    hipViewKickPitchMin\\70\\hipViewKickPitchMax\\80";

/// `weapons/sp/shotgun`
pub const SHOTGUN: &str = "\
    weaponType\\bullet\\weaponClass\\spread\\fireType\\Single Shot\\penetrateType\\medium\\boltAction\\1\\\
    damage\\160\\minDamage\\15\\maxDamageRange\\256\\minDamageRange\\800\\meleeDamage\\150\\meleeTime\\0.5\\meleeDelay\\0.05\\\
    locNone\\1\\locHelmet\\1\\locHead\\1\\locNeck\\1\\locTorsoUpper\\1\\locTorsoLower\\1\\locRightArmUpper\\1\\locLeftArmUpper\\1\\locRightArmLower\\1\\locLeftArmLower\\1\\locRightHand\\1\\locLeftHand\\1\\locRightLegUpper\\1\\locLeftLegUpper\\1\\locRightLegLower\\1\\locLeftLegLower\\1\\locRightFoot\\1\\locLeftFoot\\1\\locGun\\0\\\
    fireTime\\0.283\\rechamberTime\\0.8\\clipSize\\6\\maxAmmo\\60\\startAmmo\\60\\shotCount\\8\\\
    reloadTime\\0.6\\reloadEmptyTime\\0.6\\reloadAddTime\\0\\reloadEmptyAddTime\\0\\reloadStartTime\\0.9\\reloadStartAddTime\\0.75\\reloadEndTime\\0.95\\segmentedReload\\1\\noPartialReload\\0\\reloadAmmoAdd\\1\\reloadStartAdd\\1\\\
    hipSpreadStandMin\\4\\hipSpreadMax\\4\\hipSpreadDuckedMin\\4\\hipSpreadDuckedMax\\4\\hipSpreadProneMin\\4\\hipSpreadProneMax\\4\\adsSpread\\5.5\\hipSpreadFireAdd\\0\\hipSpreadMoveAdd\\0.1\\hipSpreadTurnAdd\\0\\hipSpreadDecayRate\\5\\hipSpreadDuckedDecay\\1\\hipSpreadProneDecay\\1\\\
    adsTransInTime\\0.24\\adsTransOutTime\\0.29\\adsZoomFov\\55\\moveSpeedScale\\1\\adsMoveSpeedScale\\1.2\\sprintDurationScale\\1\\raiseTime\\0.6\\dropTime\\0.38\\firstRaiseTime\\0.6\\\
    hipViewKickPitchMin\\100\\hipViewKickPitchMax\\100";

/// `weapons/sp/doublebarrel`
pub const DOUBLEBARREL: &str = "\
    weaponType\\bullet\\weaponClass\\spread\\fireType\\Single Shot\\penetrateType\\medium\\boltAction\\0\\\
    damage\\200\\minDamage\\15\\maxDamageRange\\256\\minDamageRange\\800\\meleeDamage\\150\\meleeTime\\0.5\\meleeDelay\\0.05\\\
    locNone\\1\\locHelmet\\1\\locHead\\1\\locNeck\\1\\locTorsoUpper\\1\\locTorsoLower\\1\\locRightArmUpper\\1\\locLeftArmUpper\\1\\locRightArmLower\\1\\locLeftArmLower\\1\\locRightHand\\1\\locLeftHand\\1\\locRightLegUpper\\1\\locLeftLegUpper\\1\\locRightLegLower\\1\\locLeftLegLower\\1\\locRightFoot\\1\\locLeftFoot\\1\\locGun\\0\\\
    fireTime\\0.283\\rechamberTime\\0.8\\clipSize\\2\\maxAmmo\\60\\startAmmo\\60\\shotCount\\8\\\
    reloadTime\\3\\reloadEmptyTime\\4\\reloadAddTime\\2.65\\reloadEmptyAddTime\\0\\reloadStartTime\\0.9\\reloadStartAddTime\\0\\reloadEndTime\\0.95\\segmentedReload\\0\\noPartialReload\\0\\reloadAmmoAdd\\0\\reloadStartAdd\\0\\\
    hipSpreadStandMin\\4\\hipSpreadMax\\4\\hipSpreadDuckedMin\\4\\hipSpreadDuckedMax\\4\\hipSpreadProneMin\\4\\hipSpreadProneMax\\4\\adsSpread\\5.5\\hipSpreadFireAdd\\0\\hipSpreadMoveAdd\\0.1\\hipSpreadTurnAdd\\0\\hipSpreadDecayRate\\5\\hipSpreadDuckedDecay\\1\\hipSpreadProneDecay\\1\\\
    adsTransInTime\\0.24\\adsTransOutTime\\0.29\\adsZoomFov\\55\\moveSpeedScale\\1\\adsMoveSpeedScale\\1.2\\sprintDurationScale\\1\\raiseTime\\0.6\\dropTime\\0.38\\firstRaiseTime\\0.6\\\
    hipViewKickPitchMin\\85\\hipViewKickPitchMax\\100";

/// `weapons/sp/doublebarrel_sawed_grip`
pub const DOUBLEBARREL_SAWED_GRIP: &str = "\
    weaponType\\bullet\\weaponClass\\spread\\fireType\\Single Shot\\penetrateType\\medium\\boltAction\\0\\\
    damage\\200\\minDamage\\15\\maxDamageRange\\256\\minDamageRange\\800\\meleeDamage\\150\\meleeTime\\0.5\\meleeDelay\\0.05\\\
    locNone\\1\\locHelmet\\1\\locHead\\1\\locNeck\\1\\locTorsoUpper\\1\\locTorsoLower\\1\\locRightArmUpper\\1\\locLeftArmUpper\\1\\locRightArmLower\\1\\locLeftArmLower\\1\\locRightHand\\1\\locLeftHand\\1\\locRightLegUpper\\1\\locLeftLegUpper\\1\\locRightLegLower\\1\\locLeftLegLower\\1\\locRightFoot\\1\\locLeftFoot\\1\\locGun\\0\\\
    fireTime\\0.283\\rechamberTime\\0.8\\clipSize\\2\\maxAmmo\\60\\startAmmo\\60\\shotCount\\8\\\
    reloadTime\\3\\reloadEmptyTime\\4\\reloadAddTime\\2.65\\reloadEmptyAddTime\\0\\reloadStartTime\\0.9\\reloadStartAddTime\\0\\reloadEndTime\\0.95\\segmentedReload\\0\\noPartialReload\\0\\reloadAmmoAdd\\0\\reloadStartAdd\\0\\\
    hipSpreadStandMin\\6\\hipSpreadMax\\6\\hipSpreadDuckedMin\\4\\hipSpreadDuckedMax\\4\\hipSpreadProneMin\\4\\hipSpreadProneMax\\4\\adsSpread\\6.5\\hipSpreadFireAdd\\0\\hipSpreadMoveAdd\\0.1\\hipSpreadTurnAdd\\0\\hipSpreadDecayRate\\5\\hipSpreadDuckedDecay\\1\\hipSpreadProneDecay\\1\\\
    adsTransInTime\\0.24\\adsTransOutTime\\0.29\\adsZoomFov\\55\\moveSpeedScale\\1\\adsMoveSpeedScale\\1.2\\sprintDurationScale\\1\\raiseTime\\0.6\\dropTime\\0.38\\firstRaiseTime\\0.6\\\
    hipViewKickPitchMin\\85\\hipViewKickPitchMax\\100";

/// `weapons/sp/ray_gun`
pub const RAY_GUN: &str = "\
    weaponType\\projectile\\weaponClass\\pistol\\boltAction\\0\\\
    damage\\1000\\meleeDamage\\150\\meleeTime\\0.5\\meleeDelay\\0.05\\\
    fireTime\\0.33\\clipSize\\20\\maxAmmo\\160\\startAmmo\\160\\\
    reloadTime\\3\\reloadAddTime\\0\\noPartialReload\\0\\reloadAmmoAdd\\0\\\
    hipSpreadStandMin\\1\\hipSpreadMax\\2\\hipSpreadDuckedMin\\1\\hipSpreadDuckedMax\\2\\hipSpreadProneMin\\1\\hipSpreadProneMax\\2\\adsSpread\\0\\hipSpreadFireAdd\\1\\hipSpreadMoveAdd\\0.5\\hipSpreadTurnAdd\\0.25\\hipSpreadDecayRate\\3.25\\hipSpreadDuckedDecay\\1.25\\hipSpreadProneDecay\\1.65\\\
    adsTransInTime\\0.245\\adsTransOutTime\\0.25\\adsZoomFov\\60\\moveSpeedScale\\1\\adsMoveSpeedScale\\1\\sprintDurationScale\\1\\raiseTime\\0.8\\dropTime\\0.8\\firstRaiseTime\\0.8\\\
    explosionRadius\\64\\explosionInnerDamage\\1500\\explosionOuterDamage\\300\\projectileSpeed\\3200\\hipViewKickPitchMin\\40\\hipViewKickPitchMax\\45";
