# Mechanical translator: OAT ZoneCodeGenerator output (T4, "word size mismatch" variant,
# gen/out/T4/XAssets/*/*_load_db.cpp) -> t4_loaders_gen.py, executed by zonewalk.py runtime.
# Only Load_*, LoadArray_*, LoadPtrArray_* and LoadDynamicFill_* bodies are translated;
# FillStruct_* bodies are not needed because zonewalk decodes struct fields directly from the
# raw 32-bit bytes using t4_layouts.json.
import re, os, glob, json
HERE = os.path.dirname(os.path.abspath(__file__))
LAY = json.load(open(os.path.join(HERE, 't4_layouts.json')))
ENUMS = LAY['enums']
MISSING = set()

out = ['# AUTO-GENERATED by cpp2py.py from OAT ZoneCodeGenerator T4 loaders. Do not edit.',
       'from zonewalk import *', '']


def tr_expr(e):
    e = e.strip()
    e = re.sub(r'static_cast<size_t>\((.*)\)$', r'\1', e)
    e = e.replace('ZonePointerType::FOLLOWING', 'FOLLOWING').replace('ZonePointerType::INSERT', 'INSERT')
    e = e.replace('||', ' or ').replace('&&', ' and ')
    e = re.sub(r'!(?!=)', ' not ', e)
    # *varXPtr
    e = re.sub(r'\*var(\w+)Ptr\b', r"self.deref('\1')", e)
    # member chains: var X -> a . b [i] ...  (innermost first)
    pat = re.compile(r'(&?)var(\w+)->(\w+)((?:\.\w+|\[[^\[\]]*\])*)')
    def rep(m):
        amp, var, f, rest = m.groups()
        parts = ["'%s'" % f]
        for p in re.findall(r'\.\w+|\[[^\[\]]*\]', rest):
            if p.startswith('.'): parts.append("'%s'" % p[1:])
            else: parts.append('(%s)' % p[1:-1])
        return "G(self.v['%s'], %s)" % (var, ', '.join(parts))
    prev = None
    while prev != e:
        prev = e
        e = pat.sub(rep, e)
    e = re.sub(r"\bvar(\w+)\b", r"self.v['\1']", e)
    # enums
    e = re.sub(r'\b([A-Z][A-Z0-9_]+)\b', lambda m: str(ENUMS[m.group(1)]) if m.group(1) in ENUMS else m.group(1), e)
    e = re.sub(r'(\d+)uz\b', r'\1', e)
    e = e.replace('/', '//')
    return e


def lvalue(e):
    """return python LV(...) constructor for a C++ lvalue"""
    e = e.strip()
    m = re.fullmatch(r'\*var(\w+)Ptr', e)
    if m: return "self.deref_lv('%s')" % m.group(1)
    m = re.fullmatch(r'var(\w+)->(\w+)((?:\.\w+|\[[^\[\]]*\])*)', e)
    assert m, e
    var, f, rest = m.groups()
    parts = ["'%s'" % f]
    for p in re.findall(r'\.\w+|\[[^\[\]]*\]', rest):
        parts.append("'%s'" % p[1:] if p.startswith('.') else '(%s)' % tr_expr(p[1:-1]))
    return "LV(self.v['%s'], %s)" % (var, ', '.join(parts))


SIZEOF = {'char': 1, 'unsigned char': 1, 'const char': 1, 'bool': 1, 'cbrushedge_t': 1,
          'std::uint16_t': 2, 'std::int16_t': 2, 'ScriptString': 2, 'LeafBrush': 2, 'uint16_t': 2,
          'int': 4, 'unsigned int': 4, 'float': 4,
          'vec2_t': 8, 'vec3_t': 12, 'vec4_t': 16, 'const float[4]': 16, 'ByteVec': 3, 'UShortVec': 6,
          'XSurfaceTri16': 6, 'raw_byte16': 16, 'raw_uint128': 128, 'complex_s': 8}


def sizeof(t):
    t = t.strip()
    if t in SIZEOF: return SIZEOF[t]
    if t.startswith('__sz'): return int(t[4:])
    if t in LAY['typedefs'] and not LAY['typedefs'][t][1]: return sizeof(LAY['typedefs'][t][0])
    l = LAY['layouts'].get(t)
    if l and l['size']: return l['size']
    MISSING.add(t)
    return 0


def tr_stmt(s, scope):
    """translate one C++ statement (no trailing brace stuff). returns list of python lines"""
    s = s.strip()
    if not s or s.startswith('assert(') or s.startswith('//'): return []
    s = re.sub(r'\s*//.*$', '', s)
    if s.startswith('m_actions.'): return ['pass  # ' + s]
    m = re.fullmatch(r'm_stream\.PushBlock\((\w+)\);', s)
    if m: return ['self.S.push(%s)' % m.group(1)]
    if s == 'm_stream.PopBlock();': return ['self.S.pop()']
    m = re.fullmatch(r'FillStruct_(\w+)\(m_stream\.LoadWithFill\((\d+)\)\);', s)
    if m: return ["self.fill('%s', %s)" % m.groups()]
    m = re.fullmatch(r'FillStruct_(\w+)\(m_stream\.GetLastFill\(\)\);', s)
    if m: return ["self.fill_last('%s')" % m.group(1)]
    m = re.fullmatch(r'm_stream\.LoadPartial<(\w+)>\(var(\w+), offsetof\(\w+, \w+\)\);', s)
    if m:
        t = m.group(1)
        return ["self.fill('%s', %d)" % (t, LAY['layouts'][t]['offsets']['data'])]
    m = re.fullmatch(r'm_stream\.Load<(.+?)>\(var(\w+)\);', s)
    if m:  # single leaf struct into current var
        t = m.group(1)
        return ["self.fill('%s', %d)" % (m.group(2), sizeof(t))]
    m = re.fullmatch(r'm_stream\.Load<(.+?)>\((\*?var[^,]+?)(?:, (.+))?\);', s)
    if m:
        t, dst, cnt = m.groups()
        cnt = tr_expr(cnt) if cnt else '1'
        if re.fullmatch(r'var\w+', dst):  # leaf array into current var (LoadArray of leaf)
            return ["self.load_into_var('%s', %d, %s)" % (dst[3:], sizeof(t), cnt)]
        return ['self.load_data(%s, %d, %s)' % (lvalue(dst), sizeof(t), cnt)]
    m = re.fullmatch(r'var(\w+) = (&?)(\*?var\w+(?:->\w+(?:\.\w+|\[[^\[\]]*\])*)?);', s)
    if m:
        dstv, amp, src = m.groups()
        if dstv == 'XString':
            return ['self.xs = %s%s' % (lvalue(src), '' if amp else '.ref()')]
        if re.fullmatch(r'\*var\w+Ptr', src):
            return ["self.v['%s'] = self.deref('%s')" % (dstv, src[4:-3])]
        if src.startswith('var') and '->' not in src:
            return ["self.v['%s'] = self.v['%s']" % (dstv, src[3:])]
        return ["self.v['%s'] = %s.ref()" % (dstv, lvalue(src))]
    if s == 'LoadXString(false);':
        return ['self.load_xstring()']
    m = re.fullmatch(r'LoadXStringArray\((true|false), (.+)\);', s)
    if m: return ['self.load_xstring_array(%s, %s)' % (m.group(1).title(), tr_expr(m.group(2)))]
    m = re.fullmatch(r'const auto zonePtrType = GetZonePointerType\((.+)\);', s)
    if m:
        scope[-1]['zpt'] = 'zpt%d' % tr_stmt.counter; tr_stmt.counter += 1
        return ['%s = ptype(%s)' % (scope[-1]['zpt'], tr_expr(m.group(1)))]
    if s == 'uintptr_t toInsertLookupEntry = 0;':
        scope[-1]['tie'] = 'tie%d' % tr_stmt.counter; tr_stmt.counter += 1
        return ['%s = None' % scope[-1]['tie']]
    if s == 'toInsertLookupEntry = m_stream.InsertPointerAliasLookup();':
        return ['%s = self.S.insert_ptr()' % lookup(scope, 'tie')]
    m = re.fullmatch(r'm_stream\.SetInsertedPointerAliasLookup\(toInsertLookupEntry, (.+)\);', s)
    if m: return ['self.S.set_alias(%s, %s)' % (lookup(scope, 'tie'), tr_expr(m.group(1)))]
    m = re.fullmatch(r'(.+?) = m_stream\.(?:Alloc|AllocOutOfBlock)<.+?>\((\d+)(?:, .+)?\);', s)
    if m: return ['%s.set(self.S.alloc(%s))' % (lvalue(m.group(1)), m.group(2))]
    m = re.fullmatch(r'(.+?) = static_cast<.+?>\(m_stream\.AllocOutOfBlock\(0, allocSize\)\);', s)
    if m: return ['%s.set(self.S.alloc(0, dyn=self.dyn))' % lvalue(m.group(1))]
    m = re.fullmatch(r'm_stream\.Alloc\((\d+)\);', s)
    if m: return ['self.S.alloc(%s)' % m.group(1)]
    m = re.fullmatch(r'const auto allocSize = LoadDynamicFill_(\w+)\(m_stream\.LoadWithFill\(0\)\);', s)
    if m: return ["self.dyn = self.dynfill('%s')" % m.group(1)]
    m = re.fullmatch(r'(.+?) = m_stream\.ConvertOffsetToPointerNative\((.+)\);', s)
    if m: return ['%s.set(self.S.ptr_native(%s))' % (lvalue(m.group(1)), tr_expr(m.group(2)))]
    m = re.fullmatch(r'(.+?) = m_stream\.ConvertOffsetToPointerLookup\((.+?)\)\.(?:Expect\(\)|OrNulled\(.*\));', s)
    if m: return ['%s.set(self.S.ptr_lookup(%s))' % (lvalue(m.group(1)), tr_expr(m.group(2)))]
    m = re.fullmatch(r'(.+?) = m_stream\.ConvertOffsetToAliasLookup\((.+)\);', s)
    if m: return ['%s.set(self.S.alias_lookup(%s))' % (lvalue(m.group(1)), tr_expr(m.group(2)))]
    m = re.fullmatch(r'Loader_(\w+) loader\(m_zone, m_stream\);', s)
    if m: scope[-1]['loader'] = m.group(1); return []
    m = re.fullmatch(r'loader\.Load\((.+)\);', s)
    if m:
        a = m.group(1)
        lv = lvalue(a[1:]) if a.startswith('&') else lvalue('*' + a)
        return ["self.W.load_asset('%s', %s)" % (lookup(scope, 'loader'), lv)]
    m = re.fullmatch(r'(Load(?:Array|PtrArray)?_\w+)\((true|false)(?:, (.+))?\);', s)
    if m:
        fn, a, n = m.groups()
        return ['self.%s(%s%s)' % (fn, a.title(), ', ' + tr_expr(n) if n else '')]
    m = re.fullmatch(r'return (.+);', s)
    if m: return ['return']
    raise ValueError('untranslated: ' + s)


tr_stmt.counter = 0


def lookup(scope, k):
    for d in reversed(scope):
        if k in d: return d[k]
    raise KeyError(k)


def tr_body(lines, indent):
    py = []
    scope = [{}]
    depth = indent
    pending_single = False
    i = 0
    while i < len(lines):
        raw = lines[i].strip(); i += 1
        if not raw or raw.startswith('assert(') or raw.startswith('//'): continue
        if raw == '{':
            scope.append({}); continue
        if raw == '}':
            scope.pop(); depth -= 1; continue
        m = re.fullmatch(r'(else )?if \((.+)\)', raw) or (re.fullmatch(r'(else)', raw) and None)
        if m or raw == 'else':
            if raw == 'else':
                head = 'else:'
            else:
                cond = m.group(2)
                cz = re.fullmatch(r'zonePtrType == ZonePointerType::(\w+)(?: \|\| zonePtrType == ZonePointerType::(\w+))?', cond)
                if cz:
                    z = lookup(scope, 'zpt')
                    cond_py = ' or '.join('%s == %s' % (z, x) for x in cz.groups() if x)
                else:
                    cond_py = tr_expr(cond)
                head = ('elif ' if m.group(1) else 'if ') + cond_py + ':'
            py.append('    ' * depth + head)
            nxt = lines[i].strip() if i < len(lines) else ''
            if nxt == '{':
                depth += 1; scope.append({}); i += 1
                # empty block?
                if lines[i].strip() == '}':
                    py.append('    ' * depth + 'pass')
                    i += 1; depth -= 1; scope.pop()
            else:
                # single statement
                body = tr_stmt(nxt, scope) or ['pass']
                i += 1
                for b in body: py.append('    ' * (depth + 1) + b)
            continue
        for b in tr_stmt(raw, scope):
            py.append('    ' * depth + b)
    return py


FAS_RE = (r'(\S.*?) = m_stream\.AllocOutOfBlock<(\w+)>\((\d+), (.+?)\);\n\s*const auto fillArraySize = .*;\n'
          r'\s*const auto fill = m_stream\.LoadWithFill\((\d+) \* fillArraySize\);\n\s*for \(.*\n\s*\{\n.*\n.*\n\s*\}')
func_re = re.compile(r'^(?:void|size_t|XAssetInfo<\w+>\*) Loader_(\w+)::(\w+)\(([^)]*)\)\n\{\n(.*?)\n\}', re.M | re.S)
classes = {}
for f in sorted(glob.glob(os.path.join(HERE, 'gen', 'out', 'T4', 'XAssets', '*', '*_load_db.cpp'))):
    src = open(f, encoding='utf-8').read()
    src = re.sub(FAS_RE, lambda m: '%s = m_stream.Alloc<%s>(%s);\n        m_stream.Load<__sz%s>(%s, %s);' % (m.group(1), m.group(2), m.group(3), m.group(5), m.group(1).strip(), m.group(4)), src)
    for m in func_re.finditer(src):
        cls, fn, args, body = m.groups()
        c = classes.setdefault(cls, {'funcs': [], 'size': None, 'post': None})
        lines = body.split('\n')
        if fn.startswith('FillStruct_') or fn in ('Load', 'LoadAsset_' + cls): continue
        if fn.startswith('LoadDynamicFill_'): continue  # hand implemented in zonewalk
        if fn == 'LoadPtr_' + cls:
            mm = re.search(r'm_actions\.(\w+)\(', body)
            c['post'] = mm.group(1) if mm else None
            c['temp'] = 'XFILE_BLOCK_TEMP' in body
            continue
        if fn.startswith('LoadArray_'):
            t = fn[len('LoadArray_'):]
            mm = re.search(r'LoadWithFill\((\d+) \* count\)', body)
            if mm: esz = int(mm.group(1))
            else:
                mm = re.search(r'm_stream\.Load<(.+?)>\(var\w+, count\)', body)
                esz = sizeof(mm.group(1))
            has_load = 'Load_%s(false)' % t in body
            c['funcs'].append('    def %s(self, a, count):\n        self.load_array(%r, %d, a, count, %s)\n'
                              % (fn, t, esz, 'self.Load_%s' % t if has_load else 'None'))
            continue
        if fn.startswith('LoadPtrArray_'):
            t = fn[len('LoadPtrArray_'):]
            # loop body between "varTPtr = var;" and "var++;"
            mm = re.search(r'var%sPtr = var;\n(.*?)\n\s*var\+\+;' % re.escape(t), body, re.S)
            loop = tr_body(mm.group(1).split('\n'), 3)
            c['funcs'].append('    def %s(self, a, count):\n        self.v[%r] = self.ptr_array_begin(%r, a, count)\n'
                              '        for _i in range(count):\n            self.ptr_array_select(%r, _i)\n%s\n'
                              % (fn, t + 'Ptr', t + 'Ptr', t, '\n'.join(loop) or '            pass'))
            continue
        if fn.startswith('Load_'):
            t = fn[len('Load_'):]
            if t == cls:
                mm = re.search(r'FillStruct_\w+\(m_stream\.LoadWithFill\((\d+)\)\)', body)
                c['size'] = int(mm.group(1))
            py = tr_body(lines, 2)
            py = [l.replace("self.fill(", "self.fill(", 1) for l in py]
            # make fill() calls in "if atStreamStart" refer to target type
            c['funcs'].append('    def %s(self, atStreamStart):\n        a = atStreamStart\n%s\n'
                              % (fn, '\n'.join(py).replace('if atStreamStart:', 'if a:') or '        pass'))
            continue
        raise ValueError('unhandled fn ' + fn)

for cls, c in classes.items():
    out.append('class L_%s(LoaderBase):' % cls)
    out.append('    ASSET = %r' % cls)
    out.append('    HEADER_SIZE = %r' % c['size'])
    out.append('    POST = %r' % c['post'])
    out.append('    TEMP = %r  # header struct loaded in XFILE_BLOCK_TEMP (generic -1/-2/alias handling) vs current block' % c.get('temp', True))
    out.append('')
    out.extend(c['funcs'])
    out.append('')
out.append('LOADERS = {%s}' % ', '.join("'%s': L_%s" % (k, k) for k in classes))
src = '\n'.join(out)
src = src.replace('atStreamStart', 'a')
src = re.sub(r"\bTrue\b", 'True', src)
open(os.path.join(HERE, 't4_loaders_gen.py'), 'w').write(src)
print('MISSING sizeof:', MISSING)
print('classes', len(classes), 'lines', src.count('\n'))
