"""Prints the per-weapon tables of `WEAPONS.md` from the weapon files in a
World at War install (`main/iw_*.iwd`, `weapons/sp/<name>`; later archives override
earlier ones).

    python research/gameplay/gen_weapon_defaults.py [install_dir]

Prints the Markdown tables of WEAPONS.md. (The game's numbers are not built
into the code: `crates/zm_core/src/weapon_defaults.rs` holds hand-picked
placeholders for running without an install.)
"""
import glob
import os
import sys
import zipfile

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
INSTALL = sys.argv[1] if len(sys.argv) > 1 else r"D:/SteamLibrary/steamapps/common/Call of Duty World at War"

# (Rust const, weapon file, our id)
WEAPONS = [
    ("ZOMBIE_COLT", "zombie_colt", "m1911"),
    ("SW_357", "sw_357", "sw_357"),
    ("M1CARBINE", "m1carbine", "m1carbine"),
    ("M1GARAND", "m1garand", "m1garand"),
    ("M1GARAND_GL", "m1garand_gl", "m1garand_gl"),
    ("GEWEHR43", "gewehr43", "gewehr43"),
    ("KAR98K", "kar98k", "kar98k"),
    ("SPRINGFIELD", "springfield", "springfield"),
    ("KAR98K_SCOPED_ZOMBIE", "kar98k_scoped_zombie", "kar98k_scoped_zombie"),
    ("PTRS41_ZOMBIE", "ptrs41_zombie", "ptrs41_zombie"),
    ("THOMPSON", "thompson", "thompson"),
    ("MP40", "mp40", "mp40"),
    ("STG44", "stg44", "stg44"),
    ("PPSH", "ppsh", "ppsh"),
    ("BAR", "bar", "bar"),
    ("FG42_BIPOD", "fg42_bipod", "fg42_bipod"),
    ("MG42_BIPOD", "mg42_bipod", "mg42_bipod"),
    ("CAL30_BIPOD", "30cal_bipod", "30cal_bipod"),
    ("SHOTGUN", "shotgun", "trenchgun"),
    ("DOUBLEBARREL", "doublebarrel", "doublebarrel"),
    ("DOUBLEBARREL_SAWED_GRIP", "doublebarrel_sawed_grip", "doublebarrel_sawed_grip"),
    ("RAY_GUN", "ray_gun", "raypistol"),
]

LOCS = [
    "locNone", "locHelmet", "locHead", "locNeck", "locTorsoUpper", "locTorsoLower",
    "locRightArmUpper", "locLeftArmUpper", "locRightArmLower", "locLeftArmLower",
    "locRightHand", "locLeftHand", "locRightLegUpper", "locLeftLegUpper",
    "locRightLegLower", "locLeftLegLower", "locRightFoot", "locLeftFoot", "locGun",
]

# The keys WeaponDef::apply_weapon_file reads, in groups (one line each).
GROUPS = [
    ["weaponType", "weaponClass", "fireType", "penetrateType", "boltAction"],
    ["damage", "minDamage", "maxDamageRange", "minDamageRange", "meleeDamage", "meleeTime", "meleeDelay"],
    LOCS,
    ["fireTime", "rechamberTime", "clipSize", "maxAmmo", "startAmmo", "shotCount"],
    ["reloadTime", "reloadEmptyTime", "reloadAddTime", "reloadEmptyAddTime", "reloadStartTime",
     "reloadStartAddTime", "reloadEndTime", "segmentedReload", "noPartialReload", "reloadAmmoAdd", "reloadStartAdd"],
    ["hipSpreadStandMin", "hipSpreadMax", "hipSpreadDuckedMin", "hipSpreadDuckedMax", "hipSpreadProneMin",
     "hipSpreadProneMax", "adsSpread", "hipSpreadFireAdd", "hipSpreadMoveAdd", "hipSpreadTurnAdd",
     "hipSpreadDecayRate", "hipSpreadDuckedDecay", "hipSpreadProneDecay"],
    ["adsTransInTime", "adsTransOutTime", "adsZoomFov", "moveSpeedScale", "adsMoveSpeedScale",
     "sprintDurationScale", "raiseTime", "dropTime", "firstRaiseTime"],
    ["explosionRadius", "explosionInnerDamage", "explosionOuterDamage", "projectileSpeed",
     "hipViewKickPitchMin", "hipViewKickPitchMax"],
]


def load():
    files = {}
    for p in sorted(glob.glob(os.path.join(INSTALL, "main", "iw_*.iwd"))):
        with zipfile.ZipFile(p) as z:
            for n in z.namelist():
                if n.lower().startswith("weapons/sp/"):
                    files[n.lower()[len("weapons/sp/"):]] = z.read(n).decode("latin-1")
    out = {}
    for _, f, _ in WEAPONS:
        parts = files[f].split("\\")
        assert parts[0] == "WEAPONFILE", f
        out[f] = dict(zip(parts[1::2], parts[2::2]))
    return out


def rust(data):
    lines = [
        "//! Built-in weapon numbers, used only when no World at War install is",
        "//! found: the same values the game's own weapon files hold (`weapons/sp/`),",
        "//! as `key\\\\value` pairs in weapon-file units (inches, seconds). With an",
        "//! install every weapon re-reads them from the IWD file and the map's zone.",
        "//!",
        "//! Generated by `research/gameplay/gen_weapon_defaults.py`; values and",
        "//! sources are listed in `research/gameplay/WEAPONS.md`.",
        "",
    ]
    for const, f, _ in WEAPONS:
        d = data[f]
        lines.append(f"/// `weapons/sp/{f}`")
        lines.append(f"pub const {const}: &str = \"\\")
        for g in GROUPS:
            kv = [(k, d[k].strip()) for k in g if k in d and d[k].strip() != ""]
            if kv:
                lines.append("    " + "".join(f"{k}\\\\{v}\\\\" for k, v in kv) + "\\")
        # Drop the trailing separator of the last line.
        lines[-1] = lines[-1][: -len("\\\\\\")] + "\";"
        lines.append("")
    return "\n".join(lines)


def md(data):
    def g(d, k, default="-"):
        v = d.get(k, "").strip()
        return v if v != "" else default

    def u2m(v):
        try:
            return f"{float(v) * 0.0254:.1f}"
        except ValueError:
            return "-"

    out = []
    out.append("### Damage and fire\n")
    out.append("| Weapon (file) | Class | Fire | Damage | Min dmg | Full dmg to (in / m) | Min dmg from (in / m) | Pellets | fireTime (s) | Rechamber (s) | RPM | Penetrate |")
    out.append("|---|---|---|---|---|---|---|---|---|---|---|---|")
    for _, f, wid in WEAPONS:
        d = data[f]
        ft = float(g(d, "fireTime", "0"))
        rc = float(g(d, "rechamberTime", "0")) if g(d, "boltAction", "0") == "1" else 0.0
        rpm = 60.0 / (ft + rc) if ft + rc > 0 else 0
        out.append(
            f"| {wid} (`{f}`) | {g(d,'weaponClass')} | {g(d,'fireType','Full Auto*')} | {g(d,'damage')} | {g(d,'minDamage')} | "
            f"{g(d,'maxDamageRange')} / {u2m(g(d,'maxDamageRange'))} | {g(d,'minDamageRange')} / {u2m(g(d,'minDamageRange'))} | "
            f"{g(d,'shotCount','1')} | {g(d,'fireTime')} | {rc if rc else '-'} | {rpm:.0f} | {g(d,'penetrateType')} |"
        )
    out.append("\n### Hit-location multipliers (left = right)\n")
    out.append("| Weapon | Helmet | Head | Neck | Torso up | Torso low | Arm up | Arm low | Hand | Leg up | Leg low | Foot |")
    out.append("|---|---|---|---|---|---|---|---|---|---|---|---|")
    for _, f, wid in WEAPONS:
        d = data[f]
        ks = ["locHelmet", "locHead", "locNeck", "locTorsoUpper", "locTorsoLower", "locRightArmUpper",
              "locRightArmLower", "locRightHand", "locRightLegUpper", "locRightLegLower", "locRightFoot"]
        out.append(f"| {wid} | " + " | ".join(g(d, k) for k in ks) + " |")
    out.append("\n### Ammo and reload (seconds)\n")
    out.append("| Weapon | Clip | Max (stock) | Start | Reload | Add at | Empty reload | Empty add at (`reloadStartAddTime`) | Segmented: start / start add / end | Rounds per loop / in start |")
    out.append("|---|---|---|---|---|---|---|---|---|---|")
    for _, f, wid in WEAPONS:
        d = data[f]
        seg = g(d, "segmentedReload", "0") == "1"
        segs = f"{g(d,'reloadStartTime')} / {g(d,'reloadStartAddTime')} / {g(d,'reloadEndTime')}" if seg else "-"
        rounds = f"{g(d,'reloadAmmoAdd')} / {g(d,'reloadStartAdd')}" if seg else "-"
        out.append(
            f"| {wid} | {g(d,'clipSize')} | {g(d,'maxAmmo')} | {g(d,'startAmmo')} | {g(d,'reloadTime')} | {g(d,'reloadAddTime')} | "
            f"{g(d,'reloadEmptyTime')} | {'-' if seg else g(d,'reloadStartAddTime')} | {segs} | {rounds} |"
        )
    out.append("\n### Spread (degrees), ADS and handling\n")
    out.append("| Weapon | Hip stand min-max | Ducked | Prone | ADS | Fire add | Move add | Decay /s | ADS in / out (s) | ADS FOV | Move speed | ADS move | Sprint dur. | Raise / drop / first raise (s) |")
    out.append("|---|---|---|---|---|---|---|---|---|---|---|---|---|---|")
    for _, f, wid in WEAPONS:
        d = data[f]
        out.append(
            f"| {wid} | {g(d,'hipSpreadStandMin')}-{g(d,'hipSpreadMax')} | {g(d,'hipSpreadDuckedMin')}-{g(d,'hipSpreadDuckedMax')} | "
            f"{g(d,'hipSpreadProneMin')}-{g(d,'hipSpreadProneMax')} | {g(d,'adsSpread')} | {g(d,'hipSpreadFireAdd')} | {g(d,'hipSpreadMoveAdd')} | "
            f"{g(d,'hipSpreadDecayRate')} | {g(d,'adsTransInTime')} / {g(d,'adsTransOutTime')} | {g(d,'adsZoomFov')} | {g(d,'moveSpeedScale')} | "
            f"{g(d,'adsMoveSpeedScale')} | {g(d,'sprintDurationScale')} | {g(d,'raiseTime')} / {g(d,'dropTime')} / {g(d,'firstRaiseTime')} |"
        )
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    data = load()
    sys.stdout.write(md(data))
